<?php
/**
 * Plugin Name States: Italy Provinces
 *
 * @author 		Your Name / Your Company Name
 * @category 	Core
 * @package 	Plugin Name/Library
 * @version 	1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $states;

$states['IT'] = array(
	'AG'    => __( 'Agrigento', PLUGIN_NAME_TEXT_DOMAIN ),
    'AL' => __( 'Alessandria', PLUGIN_NAME_TEXT_DOMAIN ),
    'AN' => __( 'Ancona', PLUGIN_NAME_TEXT_DOMAIN ),
    'AO' => __( 'Aosta', PLUGIN_NAME_TEXT_DOMAIN ),
    'AR' => __( 'Arezzo', PLUGIN_NAME_TEXT_DOMAIN ),
    'AP' => __( 'Ascoli Piceno', PLUGIN_NAME_TEXT_DOMAIN ),
    'AT' => __( 'Asti', PLUGIN_NAME_TEXT_DOMAIN ),
    'AV' => __( 'Avellino', PLUGIN_NAME_TEXT_DOMAIN ),
    'BA' => __( 'Bari', PLUGIN_NAME_TEXT_DOMAIN ),
    'BT' => __( 'Barletta-Andria-Trani', PLUGIN_NAME_TEXT_DOMAIN ),
    'BL' => __( 'Belluno', PLUGIN_NAME_TEXT_DOMAIN ),
    'BN' => __( 'Benevento', PLUGIN_NAME_TEXT_DOMAIN ),
    'BG' => __( 'Bergamo', PLUGIN_NAME_TEXT_DOMAIN ),
    'BI' => __( 'Biella', PLUGIN_NAME_TEXT_DOMAIN ),
    'BO' => __( 'Bologna', PLUGIN_NAME_TEXT_DOMAIN ),
    'BZ' => __( 'Bolzano', PLUGIN_NAME_TEXT_DOMAIN ),
    'BS' => __( 'Brescia', PLUGIN_NAME_TEXT_DOMAIN ),
    'BR' => __( 'Brindisi', PLUGIN_NAME_TEXT_DOMAIN ),
    'CA' => __( 'Cagliari', PLUGIN_NAME_TEXT_DOMAIN ),
    'CL' => __( 'Caltanissetta', PLUGIN_NAME_TEXT_DOMAIN ),
    'CB' => __( 'Campobasso', PLUGIN_NAME_TEXT_DOMAIN ),
    'CI' => __( 'Carbonia-Iglesias', PLUGIN_NAME_TEXT_DOMAIN ),
    'CE' => __( 'Caserta', PLUGIN_NAME_TEXT_DOMAIN ),
    'CT' => __( 'Catania', PLUGIN_NAME_TEXT_DOMAIN ),
    'CZ' => __( 'Catanzaro', PLUGIN_NAME_TEXT_DOMAIN ),
    'CH' => __( 'Chieti', PLUGIN_NAME_TEXT_DOMAIN ),
    'CO' => __( 'Como', PLUGIN_NAME_TEXT_DOMAIN ),
    'CS' => __( 'Cosenza', PLUGIN_NAME_TEXT_DOMAIN ),
    'CR' => __( 'Cremona', PLUGIN_NAME_TEXT_DOMAIN ),
    'KR' => __( 'Crotone', PLUGIN_NAME_TEXT_DOMAIN ),
    'CN' => __( 'Cuneo', PLUGIN_NAME_TEXT_DOMAIN ),
    'EN' => __( 'Enna', PLUGIN_NAME_TEXT_DOMAIN ),
    'FM' => __( 'Fermo', PLUGIN_NAME_TEXT_DOMAIN ),
    'FE' => __( 'Ferrara', PLUGIN_NAME_TEXT_DOMAIN ),
    'FI' => __( 'Firenze', PLUGIN_NAME_TEXT_DOMAIN ),
    'FG' => __( 'Foggia', PLUGIN_NAME_TEXT_DOMAIN ),
    'FC' => __( 'Forlì-Cesena', PLUGIN_NAME_TEXT_DOMAIN ),
    'FR' => __( 'Frosinone', PLUGIN_NAME_TEXT_DOMAIN ),
    'GE' => __( 'Genova', PLUGIN_NAME_TEXT_DOMAIN ),
    'GO' => __( 'Gorizia', PLUGIN_NAME_TEXT_DOMAIN ),
    'GR' => __( 'Grosseto', PLUGIN_NAME_TEXT_DOMAIN ),
    'IM' => __( 'Imperia', PLUGIN_NAME_TEXT_DOMAIN ),
    'IS' => __( 'Isernia', PLUGIN_NAME_TEXT_DOMAIN ),
    'SP' => __( 'La Spezia', PLUGIN_NAME_TEXT_DOMAIN ),
    'AQ' => __( 'L&apos;Aquila', PLUGIN_NAME_TEXT_DOMAIN ),
    'LT' => __( 'Latina', PLUGIN_NAME_TEXT_DOMAIN ),
    'LE' => __( 'Lecce', PLUGIN_NAME_TEXT_DOMAIN ),
    'LC' => __( 'Lecco', PLUGIN_NAME_TEXT_DOMAIN ),
    'LI' => __( 'Livorno', PLUGIN_NAME_TEXT_DOMAIN ),
    'LO' => __( 'Lodi', PLUGIN_NAME_TEXT_DOMAIN ),
    'LU' => __( 'Lucca', PLUGIN_NAME_TEXT_DOMAIN ),
    'MC' => __( 'Macerata', PLUGIN_NAME_TEXT_DOMAIN ),
    'MN' => __( 'Mantova', PLUGIN_NAME_TEXT_DOMAIN ),
    'MS' => __( 'Massa-Carrara', PLUGIN_NAME_TEXT_DOMAIN ),
    'MT' => __( 'Matera', PLUGIN_NAME_TEXT_DOMAIN ),
    'ME' => __( 'Messina', PLUGIN_NAME_TEXT_DOMAIN ),
    'MI' => __( 'Milano', PLUGIN_NAME_TEXT_DOMAIN ),
    'MO' => __( 'Modena', PLUGIN_NAME_TEXT_DOMAIN ),
    'MB' => __( 'Monza e della Brianza', PLUGIN_NAME_TEXT_DOMAIN ),
    'NA' => __( 'Napoli', PLUGIN_NAME_TEXT_DOMAIN ),
    'NO' => __( 'Novara', PLUGIN_NAME_TEXT_DOMAIN ),
    'NU' => __( 'Nuoro', PLUGIN_NAME_TEXT_DOMAIN ),
    'OT' => __( 'Olbia-Tempio', PLUGIN_NAME_TEXT_DOMAIN ),
    'OR' => __( 'Oristano', PLUGIN_NAME_TEXT_DOMAIN ),
    'PD' => __( 'Padova', PLUGIN_NAME_TEXT_DOMAIN ),
    'PA' => __( 'Palermo', PLUGIN_NAME_TEXT_DOMAIN ),
    'PR' => __( 'Parma', PLUGIN_NAME_TEXT_DOMAIN ),
    'PV' => __( 'Pavia', PLUGIN_NAME_TEXT_DOMAIN ),
    'PG' => __( 'Perugia', PLUGIN_NAME_TEXT_DOMAIN ),
    'PU' => __( 'Pesaro e Urbino', PLUGIN_NAME_TEXT_DOMAIN ),
    'PE' => __( 'Pescara', PLUGIN_NAME_TEXT_DOMAIN ),
    'PC' => __( 'Piacenza', PLUGIN_NAME_TEXT_DOMAIN ),
    'PI' => __( 'Pisa', PLUGIN_NAME_TEXT_DOMAIN ),
    'PT' => __( 'Pistoia', PLUGIN_NAME_TEXT_DOMAIN ),
    'PN' => __( 'Pordenone', PLUGIN_NAME_TEXT_DOMAIN ),
    'PZ' => __( 'Potenza', PLUGIN_NAME_TEXT_DOMAIN ),
    'PO' => __( 'Prato', PLUGIN_NAME_TEXT_DOMAIN ),
    'RG' => __( 'Ragusa', PLUGIN_NAME_TEXT_DOMAIN ),
    'RA' => __( 'Ravenna', PLUGIN_NAME_TEXT_DOMAIN ),
    'RC' => __( 'Reggio Calabria', PLUGIN_NAME_TEXT_DOMAIN ),
    'RE' => __( 'Reggio Emilia', PLUGIN_NAME_TEXT_DOMAIN ),
    'RI' => __( 'Rieti', PLUGIN_NAME_TEXT_DOMAIN ),
    'RN' => __( 'Rimini', PLUGIN_NAME_TEXT_DOMAIN ),
    'RM' => __( 'Roma', PLUGIN_NAME_TEXT_DOMAIN ),
    'RO' => __( 'Rovigo', PLUGIN_NAME_TEXT_DOMAIN ),
    'SA' => __( 'Salerno', PLUGIN_NAME_TEXT_DOMAIN ),
    'VS' => __( 'Medio Campidano', PLUGIN_NAME_TEXT_DOMAIN ),
    'SS' => __( 'Sassari', PLUGIN_NAME_TEXT_DOMAIN ),
    'SV' => __( 'Savona', PLUGIN_NAME_TEXT_DOMAIN ),
    'SI' => __( 'Siena', PLUGIN_NAME_TEXT_DOMAIN ),
    'SR' => __( 'Siracusa', PLUGIN_NAME_TEXT_DOMAIN ),
    'SO' => __( 'Sondrio', PLUGIN_NAME_TEXT_DOMAIN ),
    'TA' => __( 'Taranto', PLUGIN_NAME_TEXT_DOMAIN ),
    'TE' => __( 'Teramo', PLUGIN_NAME_TEXT_DOMAIN ),
    'TR' => __( 'Terni', PLUGIN_NAME_TEXT_DOMAIN ),
    'TO' => __( 'Torino', PLUGIN_NAME_TEXT_DOMAIN ),
    'OG' => __( 'Ogliastra', PLUGIN_NAME_TEXT_DOMAIN ),
    'TP' => __( 'Trapani', PLUGIN_NAME_TEXT_DOMAIN ),
    'TN' => __( 'Trento', PLUGIN_NAME_TEXT_DOMAIN ),
    'TV' => __( 'Treviso', PLUGIN_NAME_TEXT_DOMAIN ),
    'TS' => __( 'Trieste', PLUGIN_NAME_TEXT_DOMAIN ),
    'UD' => __( 'Udine', PLUGIN_NAME_TEXT_DOMAIN ),
    'VA' => __( 'Varese', PLUGIN_NAME_TEXT_DOMAIN ),
    'VE' => __( 'Venezia', PLUGIN_NAME_TEXT_DOMAIN ),
    'VB' => __( 'Verbano-Cusio-Ossola', PLUGIN_NAME_TEXT_DOMAIN ),
    'VC' => __( 'Vercelli', PLUGIN_NAME_TEXT_DOMAIN ),
    'VR' => __( 'Verona', PLUGIN_NAME_TEXT_DOMAIN ),
    'VV' => __( 'Vibo Valentia', PLUGIN_NAME_TEXT_DOMAIN ),
    'VI' => __( 'Vicenza', PLUGIN_NAME_TEXT_DOMAIN ),
    'VT' => __( 'Viterbo', PLUGIN_NAME_TEXT_DOMAIN )
);