<?php
/**
 * Plugin Name States: Turkey
 *
 * @author 		Your Name / Your Company Name
 * @category 	Core
 * @package 	Plugin Name/Library
 * @version 	1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $states;

$states['TR'] = array(
'TR01' => __( 'Adana', PLUGIN_NAME_TEXT_DOMAIN ),
'TR02' => __( 'Ad&#305;yaman', PLUGIN_NAME_TEXT_DOMAIN ),
'TR03' => __( 'Afyon', PLUGIN_NAME_TEXT_DOMAIN ),
'TR04' => __( 'A&#287;r&#305;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR05' => __( 'Amasya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR06' => __( 'Ankara', PLUGIN_NAME_TEXT_DOMAIN ),
'TR07' => __( 'Antalya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR08' => __( 'Artvin', PLUGIN_NAME_TEXT_DOMAIN ),
'TR09' => __( 'Ayd&#305;n', PLUGIN_NAME_TEXT_DOMAIN ),
'TR10' => __( 'Bal&#305;kesir', PLUGIN_NAME_TEXT_DOMAIN ),
'TR11' => __( 'Bilecik', PLUGIN_NAME_TEXT_DOMAIN ),
'TR12' => __( 'Bing&#246;l', PLUGIN_NAME_TEXT_DOMAIN ),
'TR13' => __( 'Bitlis', PLUGIN_NAME_TEXT_DOMAIN ),
'TR14' => __( 'Bolu', PLUGIN_NAME_TEXT_DOMAIN ),
'TR15' => __( 'Burdur', PLUGIN_NAME_TEXT_DOMAIN ),
'TR16' => __( 'Bursa', PLUGIN_NAME_TEXT_DOMAIN ),
'TR17' => __( '&#199;anakkale', PLUGIN_NAME_TEXT_DOMAIN ),
'TR18' => __( '&#199;ank&#305;r&#305;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR19' => __( '&#199;orum', PLUGIN_NAME_TEXT_DOMAIN ),
'TR20' => __( 'Denizli', PLUGIN_NAME_TEXT_DOMAIN ),
'TR21' => __( 'Diyarbak&#305;r', PLUGIN_NAME_TEXT_DOMAIN ),
'TR22' => __( 'Edirne', PLUGIN_NAME_TEXT_DOMAIN ),
'TR23' => __( 'Elaz&#305;&#287;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR24' => __( 'Erzincan', PLUGIN_NAME_TEXT_DOMAIN ),
'TR25' => __( 'Erzurum', PLUGIN_NAME_TEXT_DOMAIN ),
'TR26' => __( 'Eski&#351;ehir', PLUGIN_NAME_TEXT_DOMAIN ),
'TR27' => __( 'Gaziantep', PLUGIN_NAME_TEXT_DOMAIN ),
'TR28' => __( 'Giresun', PLUGIN_NAME_TEXT_DOMAIN ),
'TR29' => __( 'G&#252;m&#252;&#351;hane', PLUGIN_NAME_TEXT_DOMAIN ),
'TR30' => __( 'Hakkari', PLUGIN_NAME_TEXT_DOMAIN ),
'TR31' => __( 'Hatay', PLUGIN_NAME_TEXT_DOMAIN ),
'TR32' => __( 'Isparta', PLUGIN_NAME_TEXT_DOMAIN ),
'TR33' => __( '&#304;&#231;el', PLUGIN_NAME_TEXT_DOMAIN ),
'TR34' => __( '&#304;stanbul', PLUGIN_NAME_TEXT_DOMAIN ),
'TR35' => __( '&#304;zmir', PLUGIN_NAME_TEXT_DOMAIN ),
'TR36' => __( 'Kars', PLUGIN_NAME_TEXT_DOMAIN ),
'TR37' => __( 'Kastamonu', PLUGIN_NAME_TEXT_DOMAIN ),
'TR38' => __( 'Kayseri', PLUGIN_NAME_TEXT_DOMAIN ),
'TR39' => __( 'K&#305;rklareli', PLUGIN_NAME_TEXT_DOMAIN ),
'TR40' => __( 'K&#305;r&#351;ehir', PLUGIN_NAME_TEXT_DOMAIN ),
'TR41' => __( 'Kocaeli', PLUGIN_NAME_TEXT_DOMAIN ),
'TR42' => __( 'Konya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR43' => __( 'K&#252;tahya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR44' => __( 'Malatya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR45' => __( 'Manisa', PLUGIN_NAME_TEXT_DOMAIN ),
'TR46' => __( 'Kahramanmara&#351;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR47' => __( 'Mardin', PLUGIN_NAME_TEXT_DOMAIN ),
'TR48' => __( 'Mu&#287;la', PLUGIN_NAME_TEXT_DOMAIN ),
'TR49' => __( 'Mu&#351;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR50' => __( 'Nev&#351;ehir', PLUGIN_NAME_TEXT_DOMAIN ),
'TR51' => __( 'Ni&#287;de', PLUGIN_NAME_TEXT_DOMAIN ),
'TR52' => __( 'Ordu', PLUGIN_NAME_TEXT_DOMAIN ),
'TR53' => __( 'Rize', PLUGIN_NAME_TEXT_DOMAIN ),
'TR54' => __( 'Sakarya', PLUGIN_NAME_TEXT_DOMAIN ),
'TR55' => __( 'Samsun', PLUGIN_NAME_TEXT_DOMAIN ),
'TR56' => __( 'Siirt', PLUGIN_NAME_TEXT_DOMAIN ),
'TR57' => __( 'Sinop', PLUGIN_NAME_TEXT_DOMAIN ),
'TR58' => __( 'Sivas', PLUGIN_NAME_TEXT_DOMAIN ),
'TR59' => __( 'Tekirda&#287;', PLUGIN_NAME_TEXT_DOMAIN ),
'TR60' => __( 'Tokat', PLUGIN_NAME_TEXT_DOMAIN ),
'TR61' => __( 'Trabzon', PLUGIN_NAME_TEXT_DOMAIN ),
'TR62' => __( 'Tunceli', PLUGIN_NAME_TEXT_DOMAIN ),
'TR63' => __( '&#350;anl&#305;urfa', PLUGIN_NAME_TEXT_DOMAIN ),
'TR64' => __( 'U&#351;ak', PLUGIN_NAME_TEXT_DOMAIN ),
'TR65' => __( 'Van', PLUGIN_NAME_TEXT_DOMAIN ),
'TR66' => __( 'Yozgat', PLUGIN_NAME_TEXT_DOMAIN ),
'TR67' => __( 'Zonguldak', PLUGIN_NAME_TEXT_DOMAIN ),
'TR68' => __( 'Aksaray', PLUGIN_NAME_TEXT_DOMAIN ),
'TR69' => __( 'Bayburt', PLUGIN_NAME_TEXT_DOMAIN ),
'TR70' => __( 'Karaman', PLUGIN_NAME_TEXT_DOMAIN ),
'TR71' => __( 'K&#305;r&#305;kkale', PLUGIN_NAME_TEXT_DOMAIN ),
'TR72' => __( 'Batman', PLUGIN_NAME_TEXT_DOMAIN ),
'TR73' => __( '&#350;&#305;rnak', PLUGIN_NAME_TEXT_DOMAIN ),
'TR74' => __( 'Bart&#305;n', PLUGIN_NAME_TEXT_DOMAIN ),
'TR75' => __( 'Ardahan', PLUGIN_NAME_TEXT_DOMAIN ),
'TR76' => __( 'I&#287;d&#305;r', PLUGIN_NAME_TEXT_DOMAIN ),
'TR77' => __( 'Yalova', PLUGIN_NAME_TEXT_DOMAIN ),
'TR78' => __( 'Karab&#252;k', PLUGIN_NAME_TEXT_DOMAIN ),
'TR79' => __( 'Kilis', PLUGIN_NAME_TEXT_DOMAIN ),
'TR80' => __( 'Osmaniye', PLUGIN_NAME_TEXT_DOMAIN ),
'TR81' => __( 'D&#252;zce', PLUGIN_NAME_TEXT_DOMAIN ),
);